=== bstut/OKUSON/server/fmTools/dtds/config.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- ==================================================================
     config.dtd - XML Document type definition for "Config.xml"
     Copyright 2003 Frank Lübeck and Max Neunhöffer
     ================================================================== -->

<!-- $Id: config.dtd,v 1.4 2003/10/10 15:41:47 luebeck Exp $ -->

<!ELEMENT Config ANY>


<!-- The following make up the "Course" section: -->

<!ELEMENT AdministratorPassword (#PCDATA)>
<!ELEMENT CourseName (#PCDATA)>
<!ELEMENT Semester (#PCDATA)>
<!ELEMENT Lecturer (#PCDATA)>
<!ELEMENT Feedback (#PCDATA)>
<!ELEMENT PossibleStudies (Option)*>
<!ELEMENT Port (#PCDATA)>
<!ELEMENT ExtraLaTeXHeader (#PCDATA)>
<!ELEMENT User1 (#PCDATA)>
<!ELEMENT User2 (#PCDATA)>
<!ELEMENT User3 (#PCDATA)>
<!ELEMENT User4 (#PCDATA)>
<!ELEMENT User5 (#PCDATA)>
<!ELEMENT User6 (#PCDATA)>
<!ELEMENT User7 (#PCDATA)>
<!ELEMENT User8 (#PCDATA)>
<!ELEMENT User9 (#PCDATA)>
<!ELEMENT IdCheckRegExp (#PCDATA)>
<!ELEMENT GuestIdRegExp (#PCDATA)>
<!ELEMENT GradingFunction (#PCDATA)>
<!ELEMENT GradingActive (#PCDATA)>

<!-- The following make up the "Installation" section: -->

<!ELEMENT AccessList (Range)*>
<!ELEMENT AdministrationAccessList (Range)*>
<!ELEMENT DocumentRoot (#PCDATA)>
<!ELEMENT ExerciseDirectories (Dir)*>
<!ELEMENT SheetDirectories (Dir)*>
<!ELEMENT GeneralMessageFile (#PCDATA)>
<!ELEMENT RegistrationFile (#PCDATA)>
<!ELEMENT SubmissionFile (#PCDATA)>
<!ELEMENT HomeworkFile (#PCDATA)>
<!ELEMENT ExamRegistrationFile (#PCDATA)>
<!ELEMENT ExamFile (#PCDATA)>
<!ELEMENT GroupFile (#PCDATA)>
<!ELEMENT MessageFile (#PCDATA)>
<!ELEMENT GroupInfoFile (#PCDATA)>
<!ELEMENT PathToDTDs (#PCDATA)>
<!ELEMENT PDFTemplate (#PCDATA)>

<!-- The following make up the "Customization" section: -->

<!ELEMENT WidthOfSheetsHTML (#PCDATA)>
<!ELEMENT WidthOfExerciseTextsHTML (#PCDATA)>
<!ELEMENT WidthOfQuestionsHTML (#PCDATA)>
<!ELEMENT WidthOfSheetsPDF (#PCDATA)>
<!ELEMENT WidthOfExerciseTextsPDF (#PCDATA)>
<!ELEMENT WidthOfQuestionsPDF (#PCDATA)>
<!ELEMENT Resolutions (#PCDATA)>
<!ELEMENT LaTeXTemplate (#PCDATA)>

<!-- The following is used for lists of directory names: -->

<!ELEMENT Dir (#PCDATA)>
<!ELEMENT Option (#PCDATA)>
<!ELEMENT Range (#PCDATA)>

=== bstut/OKUSON/Config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
 
<!-- This is the main configuration file for OKUSON. 
     Copyright (C) 2003 Frank Lübeck and Max Neunhöffer -->

<!DOCTYPE Config SYSTEM "config.dtd">

<Config>

<!-- Usually you will not have to add or remove any elements in this 
     file but just adjust the textual data between tags. Generally
     white space is removed at the beginning and end of each element.
     See the comments or the manual for explanations.

     This file contains three sections:

       Course section: 
               Every user will have to adjust the values in this section
               to customize things for the specific course.

       Installation section: 
               Only administrators who want to adjust the installation
               to special circumstances need to have a look at this
               section.
               
       Customization section: 
               In this section many aspects of OKUSON can be customized.
               WARNING: Usually one should leave this section alone.
                        He who feels inclined to change anything here
                        should know what he is doing!

-->

<!-- ====================================================================
                              Course section
     ==================================================================== -->

<!-- The following is the encrypted administrator password. Please use the
     "cryptpasswd" utility in the OKUSON home directory to encrypt some 
     password. This password is used to do administrative jobs in OKUSON
     via the web interface. The default setting is secret, please change! -->
<AdministratorPassword>
GrurqtDBINB7o
</AdministratorPassword>

<!-- The name of the course served by this directories' server: -->
<CourseName>
Lineare Algebra I
</CourseName>

<!-- The semester this course takes place in: -->
<Semester>
WS 2003/04
</Semester>

<!-- The lecturer: -->
<Lecturer>
Prof. Dr. Herbert Pahlings
</Lecturer>

<!-- A chunk of HTML code that should appear at the bottom of every page
     for feedback. Please enclose everything in a CDATA section as shown
     such that the XML parser reading this file sees only one big string. -->
<Feedback><![CDATA[
<br /><a href="mailto:frank.luebeck@math.rwth-aachen.de">
Frank Lübeck (Frank.Luebeck@Math.RWTH-Aachen.De)</a> oder
<br /><a href="mailto:max.neunhoeffer@math.rwth-aachen.de">
Max Neunhöffer (Max.Neunhoeffer@Math.RWTH-Aachen.De)</a>
]]></Feedback>

<!-- The following appears on the registration page under the entry
"Studiengang", which means the direction of studies. Note that there
is also a free form field which - when nonempty - overwrites the choice
given here. The available options appear each within an "Option" element.
The last plays a special role: It should be not a real option but
indicate that the free form field counts which is also available. -->
<PossibleStudies>
  <Option>Mathematik-Diplom</Option>
  <Option>Mathematik-Lehramt</Option>
  <Option>Physik-Diplom</Option>
  <Option>Physik-Lehramt</Option>
  <Option>Informatik-Diplom</Option>
  <Option>Schülerstudium</Option>
  <Option>Sonstiges</Option>
</PossibleStudies>

<!-- The port on which our web server listens: -->
<Port>
8000
</Port>

<!-- There are 9 optional user defined string variables <User1>, ... <User9>.
     If they are not set here, their default values are the empty
     string.

     These variables can be used for example in the web pages via tags
     <User1 /> and so on, just like <CourseName /> above. -->
<User1></User1>
     

<!-- A chunk of LaTeX header code that is put in the preamble of all
     LaTeX documents that are generated by this program. Put here all extra
     definitions like calls to "\usepackage" or common LaTeX macros 
     that you need in your exercises. See "LaTeXTemplate" below to learn 
     which facilities are included by default. This entry is optional. -->
<ExtraLaTeXHeader>
</ExtraLaTeXHeader>

<!-- The following regular expression is used to validate id's. As we use
Matrikel numbers usually we insist on numbers. For those not familiar with
regular expressions the following means that an id must start with a
digit between 1 and 9 which is followed by 4 or 5 digits from 0 to 9:
-->
<IdCheckRegExp>^[1-9][0-9]{4,5}$</IdCheckRegExp>
<!-- Another possibility could be to allow any string consisting of
letters a-z, A-Z, digits 0-9, dashes - and underscores: 

<IdCheckRegExp>^[a-zA-Z0-9_]*$</IdCheckRegExp>
-->

<!-- The following is a Python function that can decide automatically,
     whether a certain participant has acquired the "Schein", a certificate
     of participation in the course. This function is considered in two
     cases: (1) During the display of results for a participant and
     (2) During export of results. See also the next option about how
     to activate/deactivate this feature. 
     The function gets two arguments p and sl, where p is a Person object
     as described in the Data module and sl is a list for the available
     sheets. Every entry corresponds to a sheet and is a triple: first
     the sheet number, then the name, then the sheet object itself as
     described in the Exercises module. -->
<ScheinDecisionFunction>
def ScheinDecision(p,sl,mcscore,homescore,exams):
    '''This function decides, whether person p gets the Schein. sl is
       a list of sheets as returned by the function SheetList in the
       Exercises module. mcscore is the total sum of points in all
       closed sheets with counts value equal to 1. homescore is the total
       sum of points in the homework and exams is a list of length at 
       least 24 with one score corresponding to each of 24 exams (indexed
       from 0 to 23). If the participant did not take part in an exam,
       there is a zero in the corresponding position.'''
    if (mcscore+homescore >= 240 and 
        (exams[0]+exams[1] >= 50 or
         exams[2] >= 50 or
         exams[0]+exams[2] >= 50 or
         exams[1]+exams[2] >= 50)):
        return ('Sie bekommen den Schein.',1)
    else:
        return ('Sie bekommen leider keinen Schein.',0)
</ScheinDecisionFunction>

<!-- The following entry decides, whether the automatic decision about
     the Schein is active or not. Only if the numerical value of the
     following entry is non-zero the Schein decision is performed via
     the function in ScheinDecisionFunction. -->
<ScheinDecisionActive>
1
</ScheinDecisionActive>


<!-- ==================================================================== 
                          Installation section
     ==================================================================== -->

<!-- The following is a list of IP ranges of hosts that may connect to the
     server. The default is to allow all hosts access. The notation of an
     IP range is a pair of strings separated by '/'. The first entry is an 
     IPv4 address of a subnet in dotted quad string notation and the second
     the corresponding netmask in the same notation: -->
<AccessList>
<Range>0.0.0.0/0.0.0.0</Range>
</AccessList>

<!-- The following is a list of IP ranges of hosts that may connect to the
     server for the administration pages. The default is to deny all hosts 
     access accept the localhost. The notation of an IP range is a pair
     of strings separated by '/'. The first entry is an IPv4 address
     of a subnet in dotted quad string notation and the second the
     corresponding netmask in the same notation. Note that this setting
     even denies access to the localhost if one uses the hostname instead
     of "localhost" in the URL! -->
<AdministrationAccessList>
<Range>127.0.0.0/255.0.0.0</Range>
<Range>137.226.152.0/255.255.255.128</Range>
</AdministrationAccessList>

<!-- The following contains the path to the document root of the web server.
     All template files for web pages as well as subdirectories "images",
     "messages", and "errors" must be present in this directory. The path
     is either absolute or relative to the OKUSON home directory: -->
<DocumentRoot>
html
</DocumentRoot>

<!-- The following contains a list of directories where exercises are
     collected from. Enclose each path in <Dir> </Dir>. Relative paths
     are relative to the OKUSON home directory. -->
<ExerciseDirectories>
<Dir> exercises </Dir>
</ExerciseDirectories>

<!-- The following contains a list of directories where sheets are
     collected from. Enclose each path in <Dir> </Dir>. Relative paths
     are relative to the OKUSON home directory. -->
<SheetDirectories>
<Dir> sheets </Dir>
</SheetDirectories>

<!-- The name of the file where a general message which appears on every
     participant's results page is stored. The content of this file is
     pasted one to one into the xhtml file. -->
<GeneralMessageFile>
data/generalmessage.txt
</GeneralMessageFile>

<!-- The name of the file where registration information is stored:
     (usually a path relative to OKUSON's home directory, can be absolute) -->
<RegistrationFile>
data/people.txt
</RegistrationFile>

<!-- The name of the file where solution submissions are stored:         -->
<SubmissionFile>
data/submissions.txt
</SubmissionFile>    

<!-- The name of the file where results from written homework are stored: -->
<HomeworkFile>
data/homework.txt
</HomeworkFile>

<!-- The name of the file where registration for written exams are stored: -->
<ExamRegistrationFile>
data/examregistrations.txt
</ExamRegistrationFile>

<!-- The name of the file where results from written exams are stored: -->
<ExamFile>
data/exams.txt
</ExamFile>

<!-- The name of the file where information about distribution into small
     groups is stored: -->
<GroupFile>
data/groups.txt
</GroupFile>

<!-- The name of the file where private messages for participants are 
     stored: -->
<MessageFile>
data/messages.txt
</MessageFile>

<!-- The name of the file where general information on tutoring groups
